# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u540d\u79f0')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u4ef7\u683c')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('quantity', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('image', models.ImageField(max_length=50, upload_to=b'', verbose_name='\u56fe\u7247')),
            ],
        ),
    ]
