# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=50, upload_to='.', verbose_name='\u56fe\u7247'),
        ),
    ]
