# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-07 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import shoponline.apps.catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170407_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=50, upload_to=shoponline.apps.catalog.models.upload_path_handler, verbose_name='\u56fe\u7247'),
        ),
    ]
