# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170407_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
