# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u603b\u989d')),
                ('products', models.ManyToManyField(to='catalog.Product')),
            ],
        ),
    ]
